=== yannickseidel/Laborprojekt/Lab2/lectures.dtd
<!ELEMENT lectureplan   (lecture*)>
<!ELEMENT lecture       (topic+, lector+, time+, room+)>


<!ELEMENT topic         (#PCDATA)>

<!ELEMENT lector        (title, lastName, firstName)>
<!ELEMENT title         (#PCDATA)>
<!ELEMENT firstName     (#PCDATA)>
<!ELEMENT lastName      (#PCDATA)>

<!ELEMENT time          (startingTime+, endingTime+, date+)>
<!ELEMENT startingTime  (#PCDATA)>
<!ELEMENT endingTime    (#PCDATA)>
<!ELEMENT date          (#PCDATA)>

<!ELEMENT room          (building+, number+)>
<!ELEMENT building      (#PCDATA)>
<!ELEMENT number        (#PCDATA)>

=== yannickseidel/Laborprojekt/Lab2/vorlesungsplan.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE lectureplan SYSTEM "lectures.dtd">

<lectureplan>
    <lecture>
        <topic>Web Engineering</topic>
        <lector>
            <title>Dr.</title>
            <lastName>Juergen</lastName>
            <firstName>Schneider</firstName>
        </lector>
        <time>
            <startingTime>8:00</startingTime>
            <endingTime>12:15</endingTime>
            <date>26.01.2023</date>
        </time>
        <room>
            <building>H</building>
            <number>213</number>
        </room>
    </lecture>

    <lecture>
        <topic>BWL</topic>
        <lector>
            <title>Herr</title>
            <lastName>Andreas</lastName>
            <firstName>Haag</firstName>
        </lector>
        <time>
            <startingTime>13:15</startingTime>
            <endingTime>17:15</endingTime>
            <date>26.01.2023</date>
        </time>
        <room>
            <building>H</building>
            <number>222</number>
        </room>
    </lecture>
</lectureplan>
